---
apiVersion: v1
kind: Service
metadata:
  name: green-version-shadow
  namespace: traffic-sample
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  green-shadow-mapping
      prefix:  /blue/
      service: green-version-shadow.traffic-sample
      shadow: true
spec:
  ports:
  - name: http-bg-s
    port: 80
    targetPort: bg-s
  selector:
    app: bg-s

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bg-s
  namespace: traffic-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bg-s
  template:
    metadata:
      labels:
        app: bg-s
    spec:
      imagePullSecrets:
        - name: registry
        - name: private-registry
      containers:
      - name: bg-s
#        image: nginx
        image: private-registry.micropaas.accenture.com/sample/nginx-bg:v2
        ports:
        - containerPort: 80
          name: bg-s
